### ISSUE TITLE
la pagina non esiste più 

### ISSUE THREAD

**Issue by DioBrando-33** [Metgraph/RewardsEdge#4]
All'avvio non trova la pagina per windows rewards.

**Comment by Metgraph** [comment]
**IT**
Aggiornato il programma alla nuova pagina di Microsoft rewards, puoi scaricare la nuova versione [qui](https://github.com/Metgraph/RewardsEdge/releases/tag/v1.0.2)
**EN**
The program have been updated to support the new Microsoft rewards page, now you can install the new version [here](https://github.com/Metgraph/RewardsEdge/releases/tag/v1.0.2)
